project:
  type: website
  output-dir: "docs/"

lang: "pt"  
  

website:
  title: "Exemplo para a aula de relatórios"
  sidebar: true
  navbar:
    background: "#b19cd9"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

